FlowersSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
]
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carts/urls.py
from django.urls import path
from carts import views

app_name = "carts"

urlpatterns = [
    path("cart_add/<slug:product_slug>/", views.cart_add, name="cart_add"),
    path("cart_change/<slug:product_slug>/", views.cart_change, name="cart_change"),
    path("cart_remove/<slug:product_slug>/", views.cart_remove, name="cart_remove"),
]

goods/urls.py
from django.urls import path
from goods import views

app_name = "goods"

urlpatterns = [
    path("<slug:category_slug>/", views.catalog, name="index"),
    path("product/<slug:product_slug>/", views.product, name="product"),
]

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

goods/models.py
from django.db import models


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )

    class Meta:
        db_table = "category"
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"

    def __str__(self):
        return self.name


class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name="Название")
    slug = models.SlugField(
        max_length=200, unique=True, blank=True, null=True, verbose_name="URL"
    )
    description = models.TextField(blank=True, null=True, verbose_name="Описание")
    image = models.ImageField(
        upload_to="goods_images", blank=True, null=True, verbose_name="Изображение"
    )
    price = models.IntegerField(default=0, verbose_name="Цена")
    discount = models.IntegerField(default=0, verbose_name="Скидка в процентах")
    quantity = models.PositiveIntegerField(default=0, verbose_name="Количество")
    category = models.ForeignKey(
        to=Categories, on_delete=models.CASCADE, verbose_name="Категория"
    )
    visibility = models.BooleanField(verbose_name="Отображение товара", default=True)

    class Meta:
        db_table = "product"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"
        ordering = ("id",)

    def __str__(self):
        return f"{self.name} Количество - {self.quantity}"

    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100)
        return self.price

goods/views.py
from django.shortcuts import render, get_list_or_404
from goods.models import Products


def catalog(request, category_slug):
    if category_slug == "all":
        goods = Products.objects.all()
    else:
        goods = get_list_or_404(Products.objects.filter(category__slug=category_slug))

    context = {
        "title": "Каталог",
        "goods": goods,
    }
    return render(request, "goods/catalog.html", context)


def product(request, product_slug):
    product = Products.objects.get(slug=product_slug)
    context = {"product": product}
    return render(request, "goods/product.html", context=context)

goods/templates/goods/catalog.html
{% extends "base.html" %}
{% load static %}
{% load goods_tags %}

{% block modal_cart %}
    {% include 'include/cart_button.html' %}
{% endblock %}
{% block content %}
    <div class="row">
        <!-- Форма фильтров -->
        <div class="dropdown mb-2">

            <form action="" method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on">
                    <input type="hidden" name="q" value="request.GET.q">
                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default"
                           checked>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price">
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price">
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>

        {% for product in goods %}
            <!-- Карта товара -->
            {% if product.visibility %}
                <div class="col-lg-4 col-md-6 p-4">
                    <div class="card border-primary rounded custom-shadow">
                        {% if product.image %}
                            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}">
                        {% endif %}
                        <div class="card-body">
                            <a href="{% url "catalog:product" product.slug %}">
                                <p class="card-title">{{ product.name }}</p>
                            </a>
                            <p class="card-text">{{ product.description|truncatechars:33 }}</p>
                            <div class="d-flex justify-content-between">

                                {% if product.discount %}
                                    <p><s>{{ product.price }}</s> ₽</p>
                                    <p><strong> {{ product.sell_price }} </strong>₽</p>
                                    <span class="badge bg-warning text-dark">Скидка {{ product.discount }}%</span>
                                {% else %}
                                    <p><strong>{{ product.price }}</strong>₽</p>
                                {% endif %}

                                <a href="{% url "cart:cart_add" product.slug %}" class="btn">
                                    <img class="mx-1" src="{% static "deps/icons/cart-plus.svg" %}" alt="Catalog Icon"
                                         width="32" height="32">
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}

    </div>
{% endblock %}

{% block footer %}
    <footer class="py-4 bg-dark">
        <div class="container">
            <p class="m-0 text-center text-white">Copyright &copy; Home Python Hub Studio 2023</p>
        </div>
    </footer>
{% endblock %}

goods/templates/goods/product.html
{% extends "base.html" %}
{% load static %}

{% block modal_cart %}
    {% include 'include/cart_button.html' %}
{% endblock %}

{% block content %}
    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    <img src="{{ product.image.url }}"
                         class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                     aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">{{ product.name }}</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                        aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                     class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Цена: <strong>{{ product.sell_price }}₽</strong></p>
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url "cart:cart_add" product.slug %}" class="btn btn-dark add-to-cart">Добавить в корзину</a>
            </div>
        </div>
    </div>
{% endblock %}