FlowersSite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls", namespace="main")),
    path("catalog/", include("goods.urls", namespace="catalog")),
    path("user/", include("users.urls", namespace="user")),
    path("cart/", include("carts.urls", namespace="cart")),
]
if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from main import views

app_name = 'main'

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about')
]

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.register_or_login, name="register_or_login"),
    path("logout/", views.logout, name="logout"),
    path("users-cart/", views.users_cart, name="users-cart"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    class Meta:
        db_table = "user"
        verbose_name = "Пользователя"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from users.models import User


class UserRegistrationForm(UserCreationForm):

    username = forms.CharField()
    email = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")


class UserLoginForm(AuthenticationForm):
    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ["username", "password"]

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from users.forms import UserLoginForm, UserRegistrationForm
from django.urls import reverse


def register_or_login(request):
    if request.method == "POST":
        registr_form = UserRegistrationForm(data=request.POST)
        login_form = UserLoginForm(data=request.POST)
        if login_form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            log_user = auth.authenticate(username=username, password=password)
            if log_user:
                auth.login(request, log_user)
                messages.success(request, username, "Вы успешно вышли в аккаунт")
                redirect_page = request.POST.get("next", None)
                if redirect_page and redirect_page != reverse("user:logout"):
                    return HttpResponseRedirect(request.POST.get("next"))

                return HttpResponseRedirect(reverse("main:index"))
        elif registr_form.is_valid():
            registr_form.save()
            user = registr_form.save()
            auth.login(request, user)
            messages.success(request, user.username, "Вы успешно вышли в аккаунт")
            return HttpResponseRedirect(reverse("main:index"))
    else:
        registr_form = UserRegistrationForm()
        login_form = UserLoginForm()
    return render(
        request,
        "users/login.html",
        {
            "registr_form": registr_form,
            "login_form": login_form,
            "title": "Регистрация",
        },
    )


def users_cart(request):
    return render(request, "users/users_cart.html")


@login_required
def logout(request):
    messages.success(request, f"{request.user.username}, Вы вышли из аккаунта")
    auth.logout(request)
    return redirect(reverse("main:index"))

users/templates/users/login.html
{% load static %}
{% load goods_tags %}
<!DOCTYPE html>
<html lang="es" dir="ltr">
<head>
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0">
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static "deps/css/login.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;700;800&display=swap" rel="stylesheet">
    <title>{{ title }}</title>
</head>
<body>
<div class="main">
    <div class="container a-container is-txl" id="a-container">
        <form class="form" id="a-form" method="post" action="{% url "user:register_or_login" %}">
            {% csrf_token %}
            {% if request.GET.next %}
                <input type="hidden" name="next" value="{{ request.GET.next }}">
            {% endif %}
            <h2 class="form_title title">Создать аккаунт</h2>
            <img class="flower" src="https://image.ibb.co/d5X6pn/1357d638624297b.jpg" alt="flower">
            <div>
                <input id="id_username" name="username" class="form__input" type="text" required placeholder="Ваше имя"
                       value="{% if registr_form.username.value %}{{ registr_form.username.value }}{% endif %}">
                {% if registr_form.username.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ registr_form.username.errors }}</div>
                {% endif %}
            </div>
            <div>
                <input id="id_email" class="form__input" name="email" type="email" required
                       placeholder="Электронная почта"
                       value="{% if registr_form.email.value %}{{ registr_form.email.value }}{% endif %}">
                {% if registr_form.email.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ registr_form.email.errors }}</div>
                {% endif %}
            </div>
            <div>
                <input id="id_password1" name="password1" class="form__input" type="password" placeholder="Пароль"
                       required>
                {% if registr_form.password1.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ registr_form.password1.errors }}</div>
                {% endif %}
            </div>
            <div>
                <input id="id_password2" name="password2" class="form__input" type="password"
                       placeholder="Подтвердите пароль" required>
                {% if registr_form.password2.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ registr_form.password2.errors }}</div>
                {% endif %}
            </div>
            <button type="submit" class="post_button button">Зарегистрироваться</button>
        </form>
    </div>
    <div class="container b-container is-txl is-z200" id="b-container">
        <form class="form" id="b-form" method="post" action="{% url "users:register_or_login" %}">
            {% csrf_token %}
            <h2 class="form_title title">Войти в личный кабинет</h2>
            <img class="flower" src="https://preview.ibb.co/jvu2Un/0057c1c1bab51a0.jpg" alt="flower"/>
            {% if login_form.non_field_errors %}
                <p>{{ login_form.non_field_errors }}</p>
            {% endif %}
            <div>
                <input id="id_username" name="username" class="form__input" type="text" placeholder="Имя пользователя"
                       value="{% if login_form.username.value %}{{ login_form.username.value }}{% endif %}" required>
                {% if login_form.username.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ login_form.username.errors }}</div>
                {% endif %}
            </div>
            <div>
                <input id="id_password" name="password" class="form__input" type="password" placeholder="Пароль"
                       required>
                {% if login_form.password.errors %}
                    <div class="alert alert-danger alert-dismissible fade show">{{ login_form.password.errors }}хуй</div>
                {% endif %}
            </div>
            <a class="form__link">Забыли пароль?</a>
            <button type="submit" class="post_button button">Войти</button>
        </form>
    </div>
    <div class="switch is-txr" id="switch-cnt">
        <img src="{% static "deps/image/blue flowers.jpeg" %}" alt="">
        <div class="switch__circle"></div>
        <div class="switch__circle switch__circle--t"></div>
        <div class="switch__container" id="switch-c1">
            <h2 class="switch__title title">Welcome back!</h2>
            <button class="switch__button button switch-btn">Войти</button>
        </div>
        <div class="switch__container is-hidden" id="switch-c2">
            <h2 class="switch__title title">Hello Friend !</h2>
            <button class="switch__button button switch-btn">Зарегистрироваться</button>
        </div>

    </div>

</div>
<script src="{% static "deps/js/login.js" %}"></script>
</body>
</html>

users/templates/users/logout.html
{% extends "base.html" %}
{% load static %}

users/templates/users/profile.html
{% extends "base.html" %}
{% load static %}

users/templates/users/users_cart.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                    <h3 class="text-center mb-4">Корзина</h3>
                    <div class="container" id="cart-items-container">
                        <!-- Разметка корзины -->
                        {% include 'carts/include/included_cart.html' %}
                        <!-- Закончилась разметка корзины -->
                    </div>
                    <a class="btn btn-dark" href="../orders/create_order.html">
                        Оформить заказ
                    </a>
                </div>
            </div>
        </div>
    </div>

{% endblock %}